name: Flutter Test

on:
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:
  workflow_call:

concurrency: 
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      lib: ${{ steps.filter.outputs.lib }}
      test: ${{ steps.filter.outputs.test }}
      android: ${{ steps.filter.outputs.android }}
      linux: ${{ steps.filter.outputs.linux }}
      macos: ${{ steps.filter.outputs.macos }}
      yaml: ${{ steps.filter.outputs.yaml }}
      windows: ${{ steps.filter.outputs.windows }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          lib:
            - 'lib/**'
          android:
            - 'android/**'
          test:
            - 'test/**'
          linux:
            - 'linux/**'
          macos:
            - 'macos/**'
          yaml:
            - '*.yaml'
          windows:
            - 'windows/**'
            
  android-linux-build:
    name: 'Android / Linux Build'
    needs: changes
    if: ${{ needs.changes.outputs.lib == 'true' || needs.changes.outputs.test == 'true' || needs.changes.outputs.android == 'true' || needs.changes.outputs.linux == 'true' || needs.changes.outputs.yaml == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
      - name: Flutter action
        uses: subosito/flutter-action@v2.8.0
        with:
          channel: stable
      - name: Flutter version
        run: flutter --version
      - name: Cache pubspec dependencies
        uses: actions/cache@v3.0.7
        with:
          path: |
            ${{ env.FLUTTER_HOME }}/.pub-cache
            **/.packages
            **/.flutter-plugins
            **/.flutter-plugin-dependencies
            **/.dart_tool/package_config.json
          key: build-pubspec-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            build-pubspec-
      - name: Cache build runner
        uses: actions/cache@v2
        with:
          path: |
            **/.dart_tool
            **/*.g.dart
            **/*.mocks.dart
            **/*.config.dart
          key: build-runner-${{ hashFiles('**/asset_graph.json', '**/*.dart', '**/pubspec.lock', '**/outputs.json') }}
          restore-keys: |
            build-runner-
      - name: Download pub dependencies
        run: flutter pub get
      - name: Upgrade pub dependencies
        run: flutter pub upgrade
      - name: Run build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Run analyzer
        run: flutter analyze
      - name: Run tests
        run: flutter test
      - name: Build Android
        if: ${{ needs.changes.outputs.lib == 'true' || needs.changes.outputs.test == 'true' || needs.changes.outputs.android == 'true' || needs.changes.outputs.yaml == 'true' }}
        run: |
          flutter build apk --debug --flavor dev
          
      # Run only if test, lib, and linux folder is changed
      - name: Install Linux dependencies
        if: ${{ needs.changes.outputs.lib == 'true' || needs.changes.outputs.test == 'true' || needs.changes.outputs.linux == 'true' || needs.changes.outputs.yaml == 'true' }}
        run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      - name: Build Linux 
        if: ${{ needs.changes.outputs.lib == 'true' || needs.changes.outputs.test == 'true' || needs.changes.outputs.linux == 'true' || needs.changes.outputs.yaml == 'true' }}
        run: flutter build linux
  
  macos-build:
    name: 'Macos Build'
    needs: changes
    if: ${{ needs.changes.outputs.lib == 'true' || needs.changes.outputs.test == 'true' || needs.changes.outputs.macos == 'true' || needs.changes.outputs.yaml == 'true' }}
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Flutter action
        uses: subosito/flutter-action@v2.8.0
        with:
          channel: stable
          
      - name: Flutter version
        run: flutter --version

      - name: Cache pubspec dependencies
        uses: actions/cache@v3.0.7
        with:
          path: |
            ${{ env.FLUTTER_HOME }}/.pub-cache
            **/.packages
            **/.flutter-plugins
            **/.flutter-plugin-dependencies
            **/.dart_tool/package_config.json
          key: build-pubspec-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            build-pubspec-
      - name: Cache build runner
        uses: actions/cache@v2
        with:
          path: |
            **/.dart_tool
            **/*.g.dart
            **/*.mocks.dart
            **/*.config.dart
          key: build-runner-${{ hashFiles('**/asset_graph.json', '**/*.dart', '**/pubspec.lock', '**/outputs.json') }}
          restore-keys: |
            build-runner-

      - name: Download pub dependencies
        run: flutter pub get

      - name: Upgrade pub dependencies
        run: flutter pub upgrade

      - name: Run build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run analyzer
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build macos
        run: flutter build macos

  windows-build:
    name: 'Windows Build'
    needs: changes
    if: ${{ needs.changes.outputs.lib == 'true' || needs.changes.outputs.test == 'true' || needs.changes.outputs.windows == 'true' || needs.changes.outputs.yaml == 'true' }}
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Flutter action
        uses: subosito/flutter-action@v2.8.0
        with:
          channel: stable

      - name: Download pub dependencies
        run: flutter pub get
      
      - name: Upgrade pub dependencies
        run: flutter pub upgrade

      - name: Run build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run analyzer
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build windows
        run: flutter build windows