name: Flutter Unit Tests

on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: flutter-unit-tests-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  flutter-unit-test:
    name: Unit Tests on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Bootstrap Flutter
        uses: ./.github/actions/flutter-bootstrap
        with:
          java_version: ${{ matrix.os != 'macos' && '17' || '' }}

      - name: Run analyzer
        run: flutter analyze

      - name: Run unit tests
        run: flutter test