name: Flutter Test

on:
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:
  workflow_call:

concurrency: 
  group: ${{ github.head_ref || github.run_id}}
  cancel-in-progress: true

jobs:
  changes:
    name: 'Detect changes'
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      lib: ${{ steps.filter.outputs.lib == 'true' }}
      test: ${{ steps.filter.outputs.test == 'true' }}
      android: ${{ steps.filter.outputs.android == 'true' }}
      linux: ${{ steps.filter.outputs.linux == 'true' }}
      macos: ${{ steps.filter.outputs.macos == 'true' }}
      yaml: ${{ steps.filter.outputs.yaml == 'true' }}
      windows: ${{ steps.filter.outputs.windows == 'true' }}
      branch: ${{steps.extract_branch.outputs.branch}}
    steps:
    # For pull requests it's not necessary to checkout the code
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          lib:
            - 'lib/**'
          android:
            - 'android/**'
          test:
            - 'test/**'
          linux:
            - 'linux/**'
          macos:
            - 'macos/**'
          yaml:
            - '*.yaml'
          windows:
            - 'windows/**'
  
  flutter-test:
    name: 'Flutter Analyze + Test'
    strategy:
      matrix:
        os: [macos, ubuntu, windows]
    needs: changes
    if: ${{ needs.changes.outputs.lib  || needs.changes.outputs.test  || needs.changes.outputs.yaml  || needs.changes.outputs.android  || needs.changes.outputs.linux  || needs.changes.outputs.macos  || needs.changes.outputs.windows  }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: '17'
      - name: Flutter action
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: stable
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
          pub-cache-key: "flutter-pub-:os:-:channel:-:version:-:arch:-:hash:"
          pub-cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
      - name: Flutter version
        run: flutter --version
      - name: Cache build runner
        uses: actions/cache@v4.0.2
        with:
          path: |
            **/.dart_tool
            **/*.g.dart
            **/*.mocks.dart
            **/*.config.dart
          key: build-runner-${{ hashFiles('**/asset_graph.json', '**/*.dart', '**/pubspec.lock', '**/outputs.json') }}
          restore-keys: |
            build-runner-${{ hashFiles('**/asset_graph.json', '**/*.dart', '**/pubspec.lock', '**/outputs.json') }}
            build-runner-
      - name: Download pub dependencies
        run: flutter pub get
      - name: Run build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Run analyzer
        run: flutter analyze
      - name: Install coverage tools
        run: flutter pub global activate coverage
      - name: Run tests
        run: flutter test
      - name: Install Linux dependencies
        if: ${{ (matrix.os == 'ubuntu') && (needs.changes.outputs.branch == 'dev')  && (needs.changes.outputs.lib  || needs.changes.outputs.test  || needs.changes.outputs.linux  || needs.changes.outputs.yaml ) }}
        run: sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev libssl-dev keybinder-3.0 libnotify-dev libmpv-dev mpv network-manager
         
      - name: Run integration tests for Linux
        if: needs.changes.outputs.branch == 'dev' && matrix.os == 'ubuntu'
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          flutter test integration_test/app_test.dart  --coverage -d linux
        shell: bash

      - name: Run integration tests for macos/windows
        if: needs.changes.outputs.branch == 'dev' && matrix.os != 'ubuntu'
        run: flutter test integration_test/app_test.dart  --coverage -d ${{ matrix.os }} 
          
      - name: Upload Coverage to CodeCov
        if: needs.changes.outputs.branch == 'dev'
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: coverage/lcov.info

  flutter_build:
    name: 'Build flutter'
    strategy:
      matrix:
        os: [macos, windows, ubuntu]
    needs: [changes, flutter-test]
    if: ${{ (needs.changes.outputs.lib  || needs.changes.outputs.test  || needs.changes.outputs.android  || needs.changes.outputs.linux  || needs.changes.outputs.macos  || needs.changes.outputs.windows  || needs.changes.outputs.yaml ) && (needs.changes.outputs.branch == 'dev') }}
    runs-on: ${{ matrix.os }}-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: '17'
      - name: Flutter action
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: stable
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
          pub-cache-key: "flutter-pub-:os:-:channel:-:version:-:arch:-:hash:"
          pub-cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
      - name: Cache build runner
        uses: actions/cache@v4.0.2
        with:
          path: |
            **/.dart_tool
            **/*.g.dart
            **/*.mocks.dart
            **/*.config.dart
          key: build-runner-${{ hashFiles('**/asset_graph.json', '**/*.dart', '**/pubspec.lock', '**/outputs.json') }}
          restore-keys: |
            build-runner-${{ hashFiles('**/asset_graph.json', '**/*.dart', '**/pubspec.lock', '**/outputs.json') }}
            build-runner-
      - name: Cache pods
        if: ${{ (matrix.os == 'macos') && (needs.changes.outputs.branch == 'dev') && (needs.changes.outputs.lib  || needs.changes.outputs.test  || needs.changes.outputs.macos  || needs.changes.outputs.yaml  ) }}
        uses: actions/cache@v3
        with:
          path: macos/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
            ${{ runner.os }}-pods-
      - name: Download pub dependencies
        run: flutter pub get
      - name: Run build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Build Android
        if: ${{ (matrix.os == 'ubuntu') && (needs.changes.outputs.branch == 'dev')  && (needs.changes.outputs.lib  || needs.changes.outputs.test  || needs.changes.outputs.android  || needs.changes.outputs.yaml  )}}
        run: |
          flutter build apk --debug --flavor dev
          
      # Run only if test, lib, and linux folder is changed
      - name: Install Linux dependencies
        if: ${{ (matrix.os == 'ubuntu') && (needs.changes.outputs.branch == 'dev')  && (needs.changes.outputs.lib  || needs.changes.outputs.test  || needs.changes.outputs.linux  || needs.changes.outputs.yaml ) }}
        run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      - name: Build Linux 
        if: ${{ (needs.changes.outputs.branch == 'dev') && (needs.changes.outputs.lib  || needs.changes.outputs.test  || needs.changes.outputs.linux  || needs.changes.outputs.macos  || needs.changes.outputs.windows  || needs.changes.outputs.yaml ) }}
        run: flutter build ${{ matrix.os == 'ubuntu' && 'linux' || matrix.os }}