name: Flutter Test - Dev Branch

on:
  push:
    branches: ["store"]
  pull_request:
    branches: ["dev", "store"]
  workflow_dispatch:
  workflow_call:

concurrency: 
  group: flutter-test-dev-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  changes:
    name: 'Detect changes'
    if: ${{ github.event_name != 'workflow_dispatch' && github.event_name != 'workflow_call' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      run: ${{ steps.filter.outputs.run == 'true' }}
    steps:
      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: |
            run:
              - 'lib/**'
              - 'test/**'
              - 'integration_test/**'
              - 'android/**'
              - 'ios/**'
              - 'linux/**'
              - 'macos/**'
              - 'web/**'
              - 'windows/**'
              - 'assets/**'
              - '.github/workflows/**'
              - '.metadata'
              - 'analysis_options.yaml'
              - 'devtools_options.yaml'
              - 'flutter_native_splash.yaml'
              - 'generate_coverage.sh'
              - 'pubspec.yaml'
              - 'pubspec.lock'

  flutter-unit-test:
    name: 'Unit Tests on ${{ matrix.os }}'
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    needs: changes
    if: ${{ !cancelled() && (github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call' || needs.changes.outputs.run == 'true') }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Bootstrap Flutter
        uses: ./.github/actions/flutter-bootstrap
        with:
          java_version: ${{ matrix.os != 'macos' && '17' || '' }}

      - name: Run analyzer
        run: flutter analyze

      - name: Run unit tests
        run: flutter test
          